// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ensure_initialized`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `FlutterMessageError`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

FlutterMessageClient createMessageClient() =>
    RustLib.instance.api.crateMessageBridgeCreateMessageClient();

Future<String> connectToCliServer({
  required FlutterMessageClient client,
  required String endpointAddrStr,
  String? relayUrl,
}) => RustLib.instance.api.crateMessageBridgeConnectToCliServer(
  client: client,
  endpointAddrStr: endpointAddrStr,
  relayUrl: relayUrl,
);

Future<String> createRemoteTerminal({
  required FlutterMessageClient client,
  required String sessionId,
  String? name,
  String? shellPath,
  String? workingDir,
  required int rows,
  required int cols,
}) => RustLib.instance.api.crateMessageBridgeCreateRemoteTerminal(
  client: client,
  sessionId: sessionId,
  name: name,
  shellPath: shellPath,
  workingDir: workingDir,
  rows: rows,
  cols: cols,
);

Future<void> sendTerminalInput({
  required FlutterMessageClient client,
  required String sessionId,
  required String terminalId,
  required String input,
}) => RustLib.instance.api.crateMessageBridgeSendTerminalInput(
  client: client,
  sessionId: sessionId,
  terminalId: terminalId,
  input: input,
);

Future<void> resizeRemoteTerminal({
  required FlutterMessageClient client,
  required String sessionId,
  required String terminalId,
  required int rows,
  required int cols,
}) => RustLib.instance.api.crateMessageBridgeResizeRemoteTerminal(
  client: client,
  sessionId: sessionId,
  terminalId: terminalId,
  rows: rows,
  cols: cols,
);

Future<void> stopRemoteTerminal({
  required FlutterMessageClient client,
  required String sessionId,
  required String terminalId,
}) => RustLib.instance.api.crateMessageBridgeStopRemoteTerminal(
  client: client,
  sessionId: sessionId,
  terminalId: terminalId,
);

Future<String> createTcpForwardingSession({
  required FlutterMessageClient client,
  required String sessionId,
  required String localAddr,
  String? remoteHost,
  int? remotePort,
  required String forwardingType,
}) => RustLib.instance.api.crateMessageBridgeCreateTcpForwardingSession(
  client: client,
  sessionId: sessionId,
  localAddr: localAddr,
  remoteHost: remoteHost,
  remotePort: remotePort,
  forwardingType: forwardingType,
);

Future<void> stopTcpForwardingSession({
  required FlutterMessageClient client,
  required String sessionId,
  required String tcpSessionId,
}) => RustLib.instance.api.crateMessageBridgeStopTcpForwardingSession(
  client: client,
  sessionId: sessionId,
  tcpSessionId: tcpSessionId,
);

Future<List<FlutterRemoteTerminal>> listRemoteTerminals({
  required FlutterMessageClient client,
  required String sessionId,
}) => RustLib.instance.api.crateMessageBridgeListRemoteTerminals(
  client: client,
  sessionId: sessionId,
);

Future<void> disconnectFromCliServer({
  required FlutterMessageClient client,
  required String sessionId,
}) => RustLib.instance.api.crateMessageBridgeDisconnectFromCliServer(
  client: client,
  sessionId: sessionId,
);

Future<List<FlutterSession>> getActiveSessions({
  required FlutterMessageClient client,
}) => RustLib.instance.api.crateMessageBridgeGetActiveSessions(client: client);

Future<List<FlutterTcpForwardingSession>> getTcpForwardingSessions({
  required FlutterMessageClient client,
  required String sessionId,
}) => RustLib.instance.api.crateMessageBridgeGetTcpForwardingSessions(
  client: client,
  sessionId: sessionId,
);

/// 系统控制功能
Future<FlutterSystemStatus> getSystemStatus({
  required FlutterMessageClient client,
  required String sessionId,
}) => RustLib.instance.api.crateMessageBridgeGetSystemStatus(
  client: client,
  sessionId: sessionId,
);

/// 工具函数
String parseEndpointAddr({required String addr}) =>
    RustLib.instance.api.crateMessageBridgeParseEndpointAddr(addr: addr);

/// 测试 ticket 解析（用于调试）
String testTicketParsing({required String ticket}) =>
    RustLib.instance.api.crateMessageBridgeTestTicketParsing(ticket: ticket);

/// 解析 iroh 连接票据
String parseConnectionTicket({required String ticket}) => RustLib.instance.api
    .crateMessageBridgeParseConnectionTicket(ticket: ticket);

/// 使用票据连接到 CLI 服务器
Future<String> connectByTicket({
  required FlutterMessageClient client,
  required String ticket,
}) => RustLib.instance.api.crateMessageBridgeConnectByTicket(
  client: client,
  ticket: ticket,
);

/// 简化的连接方法 - 使用节点ID直接连接
Future<String> connectByNodeId({
  required FlutterMessageClient client,
  required String nodeIdStr,
  String? relayUrl,
}) => RustLib.instance.api.crateMessageBridgeConnectByNodeId(
  client: client,
  nodeIdStr: nodeIdStr,
  relayUrl: relayUrl,
);

/// 通过节点ID和中继URL构造 EndpointAddr
String constructEndpointAddrFromNodeInfo({
  required String nodeIdHex,
  String? relayUrl,
}) => RustLib.instance.api.crateMessageBridgeConstructEndpointAddrFromNodeInfo(
  nodeIdHex: nodeIdHex,
  relayUrl: relayUrl,
);

String formatForwardingType({required TcpForwardingType forwardingType}) =>
    RustLib.instance.api.crateMessageBridgeFormatForwardingType(
      forwardingType: forwardingType,
    );

void validateTerminalSize({required int rows, required int cols}) => RustLib
    .instance
    .api
    .crateMessageBridgeValidateTerminalSize(rows: rows, cols: cols);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<FlutterMessageClient>>
abstract class FlutterMessageClient implements RustOpaqueInterface {
  static Future<FlutterMessageClient> default_() =>
      RustLib.instance.api.crateMessageBridgeFlutterMessageClientDefault();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<FlutterMessageClient> newInstance() =>
      RustLib.instance.api.crateMessageBridgeFlutterMessageClientNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TcpForwardingType>>
abstract class TcpForwardingType implements RustOpaqueInterface {}

/// Flutter远程终端信息
class FlutterRemoteTerminal {
  final String id;
  final String? name;
  final String shellType;
  final String currentDir;
  final (int, int) size;
  final bool running;
  final BigInt createdAt;

  const FlutterRemoteTerminal({
    required this.id,
    this.name,
    required this.shellType,
    required this.currentDir,
    required this.size,
    required this.running,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      shellType.hashCode ^
      currentDir.hashCode ^
      size.hashCode ^
      running.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterRemoteTerminal &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          shellType == other.shellType &&
          currentDir == other.currentDir &&
          size == other.size &&
          running == other.running &&
          createdAt == other.createdAt;
}

/// Flutter会话信息
class FlutterSession {
  final String id;
  final String nodeId;
  final String endpointAddr;
  final String connectionId;
  final BigInt createdAt;
  final FlutterSessionType sessionType;

  const FlutterSession({
    required this.id,
    required this.nodeId,
    required this.endpointAddr,
    required this.connectionId,
    required this.createdAt,
    required this.sessionType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      nodeId.hashCode ^
      endpointAddr.hashCode ^
      connectionId.hashCode ^
      createdAt.hashCode ^
      sessionType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          nodeId == other.nodeId &&
          endpointAddr == other.endpointAddr &&
          connectionId == other.connectionId &&
          createdAt == other.createdAt &&
          sessionType == other.sessionType;
}

/// Flutter会话类型
enum FlutterSessionType { terminal, tcpForwarding, systemControl }

/// Flutter系统状态信息
class FlutterSystemStatus {
  final String status;
  final BigInt uptime;
  final int activeTerminals;
  final int activeTcpSessions;
  final BigInt memoryUsage;

  const FlutterSystemStatus({
    required this.status,
    required this.uptime,
    required this.activeTerminals,
    required this.activeTcpSessions,
    required this.memoryUsage,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      uptime.hashCode ^
      activeTerminals.hashCode ^
      activeTcpSessions.hashCode ^
      memoryUsage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSystemStatus &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          uptime == other.uptime &&
          activeTerminals == other.activeTerminals &&
          activeTcpSessions == other.activeTcpSessions &&
          memoryUsage == other.memoryUsage;
}

/// Flutter TCP转发会话信息
class FlutterTcpForwardingSession {
  final String id;
  final String localAddr;
  final String remoteEndpoint;
  final String forwardingType;
  final int activeConnections;
  final BigInt bytesSent;
  final BigInt bytesReceived;
  final BigInt createdAt;

  const FlutterTcpForwardingSession({
    required this.id,
    required this.localAddr,
    required this.remoteEndpoint,
    required this.forwardingType,
    required this.activeConnections,
    required this.bytesSent,
    required this.bytesReceived,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      localAddr.hashCode ^
      remoteEndpoint.hashCode ^
      forwardingType.hashCode ^
      activeConnections.hashCode ^
      bytesSent.hashCode ^
      bytesReceived.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterTcpForwardingSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          localAddr == other.localAddr &&
          remoteEndpoint == other.remoteEndpoint &&
          forwardingType == other.forwardingType &&
          activeConnections == other.activeConnections &&
          bytesSent == other.bytesSent &&
          bytesReceived == other.bytesReceived &&
          createdAt == other.createdAt;
}
