// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/iroh_client.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/rust_lib_app/api/iroh_client.dart';
import 'third_party/rust_lib_app/api/simple.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.rustLibAppApiIrohClientInitApp();
    await api.rustLibAppApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1483479097;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_app',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<FlutterSession>>
  crateApiIrohClientIrohClientManagerGetActiveSessions({
    required IrohClientManager that,
  });

  Future<List<FlutterTerminal>>
  crateApiIrohClientIrohClientManagerGetActiveTerminals({
    required IrohClientManager that,
  });

  Future<IrohClientManager> crateApiIrohClientIrohClientManagerNew({
    required P2PNetwork network,
  });

  Future<void> crateApiIrohClientIrohClientManagerStart({
    required IrohClientManager that,
  });

  Future<String> rustLibAppApiIrohClientConnectToPeer({required String ticket});

  Future<IrohSessionInfo> rustLibAppApiIrohClientCreateIrohClient({
    String? relayUrl,
  });

  Future<String> rustLibAppApiIrohClientCreateTerminal({
    String? name,
    String? shellPath,
    String? workingDir,
    int? rows,
    int? cols,
  });

  Future<void> rustLibAppApiIrohClientDisconnectSession({
    required String sessionId,
  });

  Future<String> rustLibAppApiIrohClientGenerateQrCode({required String data});

  Future<List<FlutterSession>> rustLibAppApiIrohClientGetActiveSessions();

  Future<List<FlutterTerminal>> rustLibAppApiIrohClientGetActiveTerminals();

  String rustLibAppApiSimpleGreet({required String name});

  Future<void> rustLibAppApiIrohClientInitApp();

  Future<void> rustLibAppApiSimpleInitApp();

  Future<void> rustLibAppApiIrohClientResizeTerminal({
    required String terminalId,
    required int rows,
    required int cols,
  });

  Future<void> rustLibAppApiIrohClientSendTerminalInput({
    required String terminalId,
    required String input,
  });

  Future<void> rustLibAppApiIrohClientStopTerminal({
    required String terminalId,
  });

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_IrohClientManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_IrohClientManager;

  CrossPlatformFinalizerArg
  get rust_arc_decrement_strong_count_IrohClientManagerPtr;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_P2PNetwork;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_P2PNetwork;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_P2PNetworkPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<FlutterSession>>
  crateApiIrohClientIrohClientManagerGetActiveSessions({
    required IrohClientManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_flutter_session,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiIrohClientIrohClientManagerGetActiveSessionsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIrohClientIrohClientManagerGetActiveSessionsConstMeta =>
      const TaskConstMeta(
        debugName: "IrohClientManager_get_active_sessions",
        argNames: ["that"],
      );

  @override
  Future<List<FlutterTerminal>>
  crateApiIrohClientIrohClientManagerGetActiveTerminals({
    required IrohClientManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_flutter_terminal,
          decodeErrorData: null,
        ),
        constMeta:
            kCrateApiIrohClientIrohClientManagerGetActiveTerminalsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiIrohClientIrohClientManagerGetActiveTerminalsConstMeta =>
      const TaskConstMeta(
        debugName: "IrohClientManager_get_active_terminals",
        argNames: ["that"],
      );

  @override
  Future<IrohClientManager> crateApiIrohClientIrohClientManagerNew({
    required P2PNetwork network,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork(
            network,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiIrohClientIrohClientManagerNewConstMeta,
        argValues: [network],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohClientManagerNewConstMeta =>
      const TaskConstMeta(
        debugName: "IrohClientManager_new",
        argNames: ["network"],
      );

  @override
  Future<void> crateApiIrohClientIrohClientManagerStart({
    required IrohClientManager that,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
            that,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiIrohClientIrohClientManagerStartConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIrohClientIrohClientManagerStartConstMeta =>
      const TaskConstMeta(
        debugName: "IrohClientManager_start",
        argNames: ["that"],
      );

  @override
  Future<String> rustLibAppApiIrohClientConnectToPeer({
    required String ticket,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(ticket, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientConnectToPeerConstMeta,
        argValues: [ticket],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientConnectToPeerConstMeta =>
      const TaskConstMeta(debugName: "connect_to_peer", argNames: ["ticket"]);

  @override
  Future<IrohSessionInfo> rustLibAppApiIrohClientCreateIrohClient({
    String? relayUrl,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(relayUrl, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_iroh_session_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientCreateIrohClientConstMeta,
        argValues: [relayUrl],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientCreateIrohClientConstMeta =>
      const TaskConstMeta(
        debugName: "create_iroh_client",
        argNames: ["relayUrl"],
      );

  @override
  Future<String> rustLibAppApiIrohClientCreateTerminal({
    String? name,
    String? shellPath,
    String? workingDir,
    int? rows,
    int? cols,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_opt_String(name, serializer);
          sse_encode_opt_String(shellPath, serializer);
          sse_encode_opt_String(workingDir, serializer);
          sse_encode_opt_box_autoadd_u_16(rows, serializer);
          sse_encode_opt_box_autoadd_u_16(cols, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientCreateTerminalConstMeta,
        argValues: [name, shellPath, workingDir, rows, cols],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientCreateTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "create_terminal",
        argNames: ["name", "shellPath", "workingDir", "rows", "cols"],
      );

  @override
  Future<void> rustLibAppApiIrohClientDisconnectSession({
    required String sessionId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientDisconnectSessionConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientDisconnectSessionConstMeta =>
      const TaskConstMeta(
        debugName: "disconnect_session",
        argNames: ["sessionId"],
      );

  @override
  Future<String> rustLibAppApiIrohClientGenerateQrCode({required String data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientGenerateQrCodeConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientGenerateQrCodeConstMeta =>
      const TaskConstMeta(debugName: "generate_qr_code", argNames: ["data"]);

  @override
  Future<List<FlutterSession>> rustLibAppApiIrohClientGetActiveSessions() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_flutter_session,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientGetActiveSessionsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientGetActiveSessionsConstMeta =>
      const TaskConstMeta(debugName: "get_active_sessions", argNames: []);

  @override
  Future<List<FlutterTerminal>> rustLibAppApiIrohClientGetActiveTerminals() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_flutter_terminal,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientGetActiveTerminalsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientGetActiveTerminalsConstMeta =>
      const TaskConstMeta(debugName: "get_active_terminals", argNames: []);

  @override
  String rustLibAppApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kRustLibAppApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> rustLibAppApiIrohClientInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kRustLibAppApiIrohClientInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> rustLibAppApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kRustLibAppApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<void> rustLibAppApiIrohClientResizeTerminal({
    required String terminalId,
    required int rows,
    required int cols,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(terminalId, serializer);
          sse_encode_u_16(rows, serializer);
          sse_encode_u_16(cols, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientResizeTerminalConstMeta,
        argValues: [terminalId, rows, cols],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientResizeTerminalConstMeta =>
      const TaskConstMeta(
        debugName: "resize_terminal",
        argNames: ["terminalId", "rows", "cols"],
      );

  @override
  Future<void> rustLibAppApiIrohClientSendTerminalInput({
    required String terminalId,
    required String input,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(terminalId, serializer);
          sse_encode_String(input, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientSendTerminalInputConstMeta,
        argValues: [terminalId, input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientSendTerminalInputConstMeta =>
      const TaskConstMeta(
        debugName: "send_terminal_input",
        argNames: ["terminalId", "input"],
      );

  @override
  Future<void> rustLibAppApiIrohClientStopTerminal({
    required String terminalId,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(terminalId, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kRustLibAppApiIrohClientStopTerminalConstMeta,
        argValues: [terminalId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kRustLibAppApiIrohClientStopTerminalConstMeta =>
      const TaskConstMeta(debugName: "stop_terminal", argNames: ["terminalId"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_IrohClientManager => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_IrohClientManager => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager;

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_P2PNetwork => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_P2PNetwork => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  IrohClientManager
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IrohClientManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PNetwork
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PNetworkImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  IrohClientManager
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IrohClientManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  IrohClientManager
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return IrohClientManagerImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PNetwork
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PNetworkImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  int dco_decode_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  FlutterSession dco_decode_flutter_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlutterSession(
      id: dco_decode_String(arr[0]),
      ticket: dco_decode_String(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      createdAt: dco_decode_u_64(arr[3]),
      status: dco_decode_String(arr[4]),
    );
  }

  @protected
  FlutterTerminal dco_decode_flutter_terminal(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FlutterTerminal(
      id: dco_decode_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      shellType: dco_decode_String(arr[2]),
      currentDir: dco_decode_String(arr[3]),
      status: dco_decode_String(arr[4]),
      createdAt: dco_decode_u_64(arr[5]),
      size: dco_decode_record_u_16_u_16(arr[6]),
    );
  }

  @protected
  IrohSessionInfo dco_decode_iroh_session_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return IrohSessionInfo(
      nodeId: dco_decode_String(arr[0]),
      nodeAddr: dco_decode_String(arr[1]),
      relayUrl: dco_decode_opt_String(arr[2]),
      isConnected: dco_decode_bool(arr[3]),
    );
  }

  @protected
  List<FlutterSession> dco_decode_list_flutter_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_flutter_session).toList();
  }

  @protected
  List<FlutterTerminal> dco_decode_list_flutter_terminal(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_flutter_terminal).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_16(raw);
  }

  @protected
  (int, int) dco_decode_record_u_16_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_u_16(arr[0]), dco_decode_u_16(arr[1]));
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  IrohClientManager
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IrohClientManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  P2PNetwork
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PNetworkImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  IrohClientManager
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IrohClientManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  IrohClientManager
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return IrohClientManagerImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  P2PNetwork
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PNetworkImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  int sse_decode_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_16(deserializer));
  }

  @protected
  FlutterSession sse_decode_flutter_session(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_ticket = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_status = sse_decode_String(deserializer);
    return FlutterSession(
      id: var_id,
      ticket: var_ticket,
      title: var_title,
      createdAt: var_createdAt,
      status: var_status,
    );
  }

  @protected
  FlutterTerminal sse_decode_flutter_terminal(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_shellType = sse_decode_String(deserializer);
    var var_currentDir = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_size = sse_decode_record_u_16_u_16(deserializer);
    return FlutterTerminal(
      id: var_id,
      name: var_name,
      shellType: var_shellType,
      currentDir: var_currentDir,
      status: var_status,
      createdAt: var_createdAt,
      size: var_size,
    );
  }

  @protected
  IrohSessionInfo sse_decode_iroh_session_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_nodeId = sse_decode_String(deserializer);
    var var_nodeAddr = sse_decode_String(deserializer);
    var var_relayUrl = sse_decode_opt_String(deserializer);
    var var_isConnected = sse_decode_bool(deserializer);
    return IrohSessionInfo(
      nodeId: var_nodeId,
      nodeAddr: var_nodeAddr,
      relayUrl: var_relayUrl,
      isConnected: var_isConnected,
    );
  }

  @protected
  List<FlutterSession> sse_decode_list_flutter_session(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterSession>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_session(deserializer));
    }
    return ans_;
  }

  @protected
  List<FlutterTerminal> sse_decode_list_flutter_terminal(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FlutterTerminal>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_flutter_terminal(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_16(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (int, int) sse_decode_record_u_16_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_u_16(deserializer);
    var var_field1 = sse_decode_u_16(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    IrohClientManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as IrohClientManagerImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork(
    P2PNetwork self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as P2PNetworkImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    IrohClientManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as IrohClientManagerImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerIrohClientManager(
    IrohClientManager self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as IrohClientManagerImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2PNetwork(
    P2PNetwork self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as P2PNetworkImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self, serializer);
  }

  @protected
  void sse_encode_flutter_session(
    FlutterSession self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.ticket, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_String(self.status, serializer);
  }

  @protected
  void sse_encode_flutter_terminal(
    FlutterTerminal self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_String(self.shellType, serializer);
    sse_encode_String(self.currentDir, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_record_u_16_u_16(self.size, serializer);
  }

  @protected
  void sse_encode_iroh_session_info(
    IrohSessionInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.nodeId, serializer);
    sse_encode_String(self.nodeAddr, serializer);
    sse_encode_opt_String(self.relayUrl, serializer);
    sse_encode_bool(self.isConnected, serializer);
  }

  @protected
  void sse_encode_list_flutter_session(
    List<FlutterSession> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_session(item, serializer);
    }
  }

  @protected
  void sse_encode_list_flutter_terminal(
    List<FlutterTerminal> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_flutter_terminal(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_16(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_16(self, serializer);
    }
  }

  @protected
  void sse_encode_record_u_16_u_16((int, int) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.$1, serializer);
    sse_encode_u_16(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class IrohClientManagerImpl extends RustOpaque implements IrohClientManager {
  // Not to be used by end users
  IrohClientManagerImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  IrohClientManagerImpl.frbInternalSseDecode(
    BigInt ptr,
    int externalSizeOnNative,
  ) : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_IrohClientManager,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_IrohClientManager,
    rustArcDecrementStrongCountPtr: RustLib
        .instance
        .api
        .rust_arc_decrement_strong_count_IrohClientManagerPtr,
  );

  Future<List<FlutterSession>> getActiveSessions() => RustLib.instance.api
      .crateApiIrohClientIrohClientManagerGetActiveSessions(that: this);

  Future<List<FlutterTerminal>> getActiveTerminals() => RustLib.instance.api
      .crateApiIrohClientIrohClientManagerGetActiveTerminals(that: this);

  Future<void> start() =>
      RustLib.instance.api.crateApiIrohClientIrohClientManagerStart(that: this);
}

@sealed
class P2PNetworkImpl extends RustOpaque implements P2PNetwork {
  // Not to be used by end users
  P2PNetworkImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  P2PNetworkImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_P2PNetwork,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PNetwork,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PNetworkPtr,
  );
}
