[package]
name = "browser"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = { workspace = true }
console_error_panic_hook = "0.1.7"
futures = { workspace = true }
serde = { workspace = true }
serde-wasm-bindgen = "0.6.5"
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-subscriber-wasm = "0.1.0"
wasm-bindgen = "=0.2"
wasm-bindgen-futures = "0.4"
wasm-streams = "0.6"
js-sys = "0.3"
web-sys = "0.3"
gloo-timers = { version = "0.4", features = ["futures"] }
async-stream = "0.3.5"
futures-util = { workspace = true }
bincode = { workspace = true }
base64 = { workspace = true }
data-encoding = { workspace = true }
n0-future = { workspace = true }
iroh = { workspace = true, default-features = false, features = ["tls-ring"] }
iroh-tickets = { workspace = true }
iroh-base = { workspace = true, default-features = false }
postcard = { workspace = true }
tokio = { version = "1.47", default-features = false, features = ["sync"] }
getrandom = { version = "0.4", features = [] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = [
  "--enable-nontrapping-float-to-int",
  "--enable-bulk-memory",
  "--enable-sign-ext",
]
