// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import '../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<IrohClientManager>>
abstract class IrohClientManager implements RustOpaqueInterface {
  Future<List<FlutterSession>> getActiveSessions();

  Future<List<FlutterTerminal>> getActiveTerminals();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<IrohClientManager> newInstance({required P2PNetwork network}) =>
      RustLib.instance.api.crateApiIrohClientIrohClientManagerNew(
        network: network,
      );

  Future<void> start();
}

class FlutterSession {
  final String id;
  final String ticket;
  final String? title;
  final BigInt createdAt;
  final String status;

  const FlutterSession({
    required this.id,
    required this.ticket,
    this.title,
    required this.createdAt,
    required this.status,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      ticket.hashCode ^
      title.hashCode ^
      createdAt.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterSession &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          ticket == other.ticket &&
          title == other.title &&
          createdAt == other.createdAt &&
          status == other.status;
}

class FlutterTerminal {
  final String id;
  final String? name;
  final String shellType;
  final String currentDir;
  final String status;
  final BigInt createdAt;
  final (int, int) size;

  const FlutterTerminal({
    required this.id,
    this.name,
    required this.shellType,
    required this.currentDir,
    required this.status,
    required this.createdAt,
    required this.size,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      name.hashCode ^
      shellType.hashCode ^
      currentDir.hashCode ^
      status.hashCode ^
      createdAt.hashCode ^
      size.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterTerminal &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          shellType == other.shellType &&
          currentDir == other.currentDir &&
          status == other.status &&
          createdAt == other.createdAt &&
          size == other.size;
}

class IrohSessionInfo {
  final String nodeId;
  final String nodeAddr;
  final String? relayUrl;
  final bool isConnected;

  const IrohSessionInfo({
    required this.nodeId,
    required this.nodeAddr,
    this.relayUrl,
    required this.isConnected,
  });

  @override
  int get hashCode =>
      nodeId.hashCode ^
      nodeAddr.hashCode ^
      relayUrl.hashCode ^
      isConnected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IrohSessionInfo &&
          runtimeType == other.runtimeType &&
          nodeId == other.nodeId &&
          nodeAddr == other.nodeAddr &&
          relayUrl == other.relayUrl &&
          isConnected == other.isConnected;
}
